config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'users/new'
  get 'games/new'
  
  resources :users
  resources :games
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :createScenarios
    
    def createScenarios 
        Game.create!(:title=>"Narrative Title 1", :text=>"This is where the narrative should be.")
        Game.create!(:title=>"Narrative Title 2", :text=>"This is where the narrative should be.")
        Game.create!(:title=>"Narrative Title 3", :text=>"This is where the narrative should be.")
        Game.create!(:title=>"Narrative Title 4", :text=>"This is where the narrative should be.")
        Game.create!(:title=>"Narrative Title 5", :text=>"This is where the narrative should be.")
        Game.create!(:title=>"Narrative Title 6", :text=>"This is where the narrative should be.")
    end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
    def new
    end
    
    def create
        render plain: params[:game].inspect
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    def show
        @game = Game.find(params[:id])
    end
    
    def index
    end
    
    def new
    end
    
    def create
        render plain: params[:game].inspect
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
      @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    createScenarios
    @user = User.new(user_params)
        #byebug
        
        if @user.save
            #byebug
            redirect_to @user
        else
            render 'index'
        end
  end
  
  def edit
        @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to @user
        else
            render 'edit'
        end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    
    redirect_to :controller => 'welcome', :action => 'index'
  end

private
    def user_params
        params.require(:user).permit(:username, :mage, :bow, :sword, :shield)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/index.html.erb
<body>
    <div>
            
        <p>Resume your journey by entering your username...</p>
        <p><input type="text" name="key"><br>
        <button onclick="getUsername()">Continue</button></p>
        
        <script>
            function getUsername() {
                return document.getElementById("myText").value;
            }
        </script>
        
        <p>OR</p>
        
        <p id="enroll"><%= link_to 'Start a new journey!', new_user_path %></p>
        
        <p><%= link_to 'Back', controller: 'welcome' %></p>
    </div>
</body>

app/views/games/show.html.erb
<body>
    <div>
        <h1><strong>Title:</strong>
        <%= @game.title %>
        </h1>
        <p>Narrative:
        <%= @game.text %>
        </p>
        
        <p><%= link_to 'Choice 1', game_path(2) %> <%= link_to 'Choice 2', game_path(3) %> <%= link_to 'Choice 3', game_path(4) %> <%= link_to 'Choice 4', game_path(5) %></p>
        
        <p><%= link_to 'Back to Main Menu', controller: 'welcome' %></p>
    </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TextBased</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<body>
    <div>
        <h1>Newest Students</h1>
        
        <% @users.reverse_each do |user| %>
            <p><%= user.username %></p>
        <% end %>
        
        <p><%= link_to 'Back', controller: 'welcome' %></p>
    </div>
</body>

app/views/users/new.html.erb
<body>
    <div>
        <h1>Enrollment</h1>
        <%= form_for :user, url: users_path do |f| %>
            <p>
                <%= f.label :username %>
                <%= f.text_field :username %>
            </p>
            <p><%= f.submit %></p>
        <% end %>
        
        <p><%= link_to 'Back', games_path %></p>
    </div>
</body>

app/views/users/show.html.erb
<body>
    <div>
        <h1>Welcome <%= @user.username %>!</h1>
        
        <p><%= link_to 'Start', game_path(1) %></p>
        <p><%= link_to 'Back to Main Menu', controller: 'welcome' %></p>
        <p><%= link_to 'End your Journey', 
                                  user_path(@user),
                                  method: :delete,
                                  data: { confirm: 'Are you sure you want to delete your character and progress?' } %></p>
        
    </div>
</body>

app/views/welcome/index.html.erb
<body>
    <div>
        <h1>Welcome to <em>Winsor Academy!</em></h1>
        
        <img src = "http://i.imgur.com/aB5rAWY.jpg?1" alt = "Fantasy school" id = "image">
        
        <h2>You may find that the Academy life is hard, try your best not to fail.</h2>
        <p> 
            <%= link_to 'Play', controller: 'games' %> <br>
            <%= link_to 'Newest Students', controller: 'users' %>
        </p> 
    </div>
</body>